name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    # Needs read & write permissions to push the built web page to GitHub
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Enable Web
        run: flutter config --enable-web

      - name: Install Dependencies
        run: flutter pub get

      - name: Clean Build
        run: flutter clean

      - name: Build Web
        run: flutter build web --release --base-href "/smart_kirana/" --no-tree-shake-icons

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
